FROM python:3.11-slim

RUN pip install poetry==1.8.2

WORKDIR /app

COPY pyproject.toml poetry.lock /app/
RUN touch README.md

RUN poetry install --no-root

COPY . /app/

RUN chmod +x /app/run.sh
CMD ["/app/run.sh"]